# John Crime (mail syndie)
- type: startingGear
  id: SyndicateFootsoldierGearMail
  equipment:
    mask: ClothingMaskNeckGaiter
    jumpsuit: ClothingUniformJumpsuitOperative
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombat
    id: SyndiPDA
  inhand:
  - ThrowingKnife

﻿# Joke Joke starting items
- type: startingGear
  id: KoboldPirateBartenderGear
  equipment:
    head: ClothingHeadBandRed
    ears: ClothingHeadsetPirate
    jumpsuit: ClothingUniformJumpsuitPirateAntag
    id: JokeJokeIDCard
  inhand:
  - WeaponPistolFlintlock
