# SPDX-FileCopyrightText: 2025 FungiFellow
# SPDX-FileCopyrightText: 2025 themias
# SPDX-FileCopyrightText: 2025 K-Dynamic
# SPDX-FileCopyrightText: 2025 T
# SPDX-FileCopyrightText: 2024 Plykiya
# SPDX-FileCopyrightText: 2024 Nemanja
# SPDX-FileCopyrightText: 2024 vorkathbruh
# SPDX-FileCopyrightText: 2024 MODERN
# SPDX-FileCopyrightText: 2022 Nairod
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 LankLTE
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2023 metalgearsloth
# SPDX-FileCopyrightText: 2023 lapatison
# SPDX-FileCopyrightText: 2023 Maxtone
# SPDX-FileCopyrightText: 2022 rolfero
# SPDX-FileCopyrightText: 2022 Myctai
# SPDX-FileCopyrightText: 2022 Rinkashikachi
# SPDX-FileCopyrightText: 2021 Mith-randalf
# SPDX-FileCopyrightText: 2021 SweptWasTaken
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-License-Identifier: MIT

- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: Clothing/OuterClothing/Armor/bulletproof.rsi
    state: icon
  product: CrateSecurityArmor
  cost: 1250
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityHelmet
  icon:
    sprite: Clothing/Head/Helmets/security.rsi
    state: icon
  product: CrateSecurityHelmet
  cost: 550
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonLethal
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  product: CrateSecurityNonlethal
  cost: 4000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecuritySupplies
  icon:
    sprite: Objects/Storage/boxes.rsi
    state: box_security
  product: CrateSecuritySupplies
  cost: 500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityRestraints
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  product: CrateRestraints
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: Clothing/Head/Hoods/Bio/security.rsi
    state: icon
  product: CrateSecurityBiosuit
  cost: 1600
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: Objects/Specific/Security/barrier.rsi
    state: idle
  product: DeployableBarrier
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonlethalThrowables
  icon:
    sprite: Objects/Weapons/Grenades/stingergrenade.rsi
    state: icon
  product: CrateSecNonlethalThrowables
  cost: 2500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityGenPopCloset
  icon:
    sprite: Structures/Storage/closet.rsi
    state: genpop
  product: LockerPrisoner
  cost: 250
  category: cargoproduct-category-name-security
  group: market
