- type: job
  id: Stowaway 
  weight: 10
  name: roles-antag-stowaway-name
  description: roles-antag-stowaway-objective
  playTimeTracker: JobStowaway
  startingGear: StowawayGear
  icon: "JobIconNoId"
  supervisors: job-supervisors-nobody
  joinNotifyCrew: false
  ignoreArrivals: true
  overrideConsoleVisibility: true
  access:
  - Maintenance 
  special:
  - !type:AddComponentSpecial
    components:
      - type: StowawayRole 

- type: playTimeTracker
  id: JobStowaway

- type: startingGear
  id: StowawayGear
  equipment:
    jumpsuit: ClothingUniformRandomStandard
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    mask: ClothingMaskGas
    #id: CardboardIDCard - Moffstation PDA loadouts
  storage:
    back:
    - FoodSnackMREBrownie
    - DrinkWaterBottleFull
