# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2022 Rinkashikachi
# SPDX-FileCopyrightText: 2022 mirrorcult
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2021 Elijahrane
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2021 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-License-Identifier: MIT

- type: accessLevel
  id: Bar
  name: id-card-access-level-bar

- type: accessLevel
  id: Kitchen
  name: id-card-access-level-kitchen

- type: accessLevel
  id: Hydroponics
  name: id-card-access-level-hydroponics

- type: accessLevel
  id: Service
  name: id-card-access-level-service

- type: accessLevel
  id: Janitor
  name: id-card-access-level-janitor

- type: accessLevel
  id: Theatre
  name: id-card-access-level-theatre

- type: accessLevel
  id: Chapel
  name: id-card-access-level-chapel

- type: accessLevel
  id: Lawyer
  name: id-card-access-level-lawyer

- type: accessGroup
  id: Service
  tags:
  - HeadOfPersonnel
  - Bar
  - Kitchen
  - Hydroponics
  - Service
  - Janitor
  - Theatre
  - Chapel
  - Lawyer
