- type: antag
  id: Stowaway
  name: roles-antag-stowaway-name
  antagonist: false
  setPreference: true
  objective: roles-antag-stowaway-objective

- type: startingGear
  id: StowawayGear
  equipment:
    jumpsuit: ClothingUniformRandomStandard
    shoes: ClothingShoesColorBlack
    mask: ClothingMaskGas
    gloves: ClothingHandsGlovesColorYellow
    id: CardboardIDCard

- type: entity
  categories: [ HideSpawnMenu, Spawner ]
  parent: BaseAntagSpawner
  id: SpawnPointGhostStowaway
  name: ghost role spawn point
  suffix: stowaway
  components:
  - type: GhostRole
    name: roles-antag-stowaway-name
    description: roles-antag-stowaway-desc
    rules: ghost-role-information-freeagent-rules
    mindRoles:
    - MindRoleGhostRoleFreeAgent
    raffle:
      settings: default
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
    - state: green
    - sprite: Clothing/Mask/gas.rsi
      state: icon
