# SPDX-FileCopyrightText: 2024 UBlueberry
# SPDX-FileCopyrightText: 2024 f0x-n3rd
# SPDX-FileCopyrightText: 2023 liltenhead
# SPDX-FileCopyrightText: 2023 Hebi
# SPDX-FileCopyrightText: 2023 Nails+Tape
# SPDX-FileCopyrightText: 2023 end
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 Sir Winters
# SPDX-FileCopyrightText: 2023 AjexRose
# SPDX-FileCopyrightText: 2023 Leon Friedrich
# SPDX-FileCopyrightText: 2023 faint
# SPDX-FileCopyrightText: 2023 Kevin Zheng
# SPDX-License-Identifier: MIT

- type: guideEntry
  id: Service
  name: guide-entry-service
  text: "/ServerInfo/Guidebook/Service/Service.xml"
  filterEnabled: True
  children:
  - Bartender
  - Botany
  - Chef
  - Janitorial
  
- type: guideEntry
  id: Bartender
  name: guide-entry-bartender
  text: "/ServerInfo/Guidebook/Service/Bartender.xml"
  filterEnabled: True

- type: guideEntry
  id: Botany
  name: guide-entry-botany
  text: "/ServerInfo/Guidebook/Service/Botany.xml"

- type: guideEntry
  id: Chef
  name: guide-entry-chef
  text: "/ServerInfo/Guidebook/Service/Chef.xml"

- type: guideEntry
  id: Janitorial
  name: guide-entry-janitorial
  text: "/ServerInfo/Guidebook/Service/Janitorial.xml"
