# SPDX-FileCopyrightText: 2025 PJB3005 <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2025 Vasilis The Pikachu <vasilis@pikachu.systems>
# SPDX-FileCopyrightText: 2025 ƒÅda <ss.adasts@gmail.com>
# SPDX-License-Identifier: MIT

- type: stack
  parent: BaseMediumStack
  id: CableDet
  name: stack-explosive-cord
  icon: { sprite: "/Textures/Objects/Tools/cable-coils.rsi", state: coilex-30 }
  spawn: CableDetStack1
