# SPDX-FileCopyrightText: 2026 Kowlin
# SPDX-FileCopyrightText: 2025 Princess Cheeseballs
# SPDX-FileCopyrightText: 2025 Hitlinemoss
# SPDX-FileCopyrightText: 2025 Mora
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2025 Errant
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2025 Minemoder5000
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 SpeltIncorrectyl
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2024 Flareguy
# SPDX-FileCopyrightText: 2024 Nairod
# SPDX-FileCopyrightText: 2023 Kevin Zheng
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 ninruB
# SPDX-FileCopyrightText: 2023 freeman2651
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Peptide90
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 VÃ­ctor Aguilera Puerto
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-License-Identifier: MIT

- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
