# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Jukereise <altjupiterfive@gmail.com>
# SPDX-FileCopyrightText: 2022 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 coolmankid12345 <55817627+coolmankid12345@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 ninruB <38016303+asperger-sind@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 freeman2651 <104049107+freeman2651@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024-2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PopGamer46 <yt1popgamer@gmail.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PotentiallyTom <67602105+PotentiallyTom@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Princess Cheeseballs <66055347+Princess-Cheeseballs@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Hitlinemoss <209321380+Hitlinemoss@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Mora <46364955+TrixxedHeart@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Minemoder5000 <minemoder50000@gmail.com>
# SPDX-FileCopyrightText: 2026 Kowlin <10947836+Kowlin@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: SecurityCadetChameleonOutfit
  job: SecurityCadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesHudSecurity
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckScarfStripedRed
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
