# SPDX-FileCopyrightText: 2020, 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020, 2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2020-2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2020 20kdc <asdd2808@gmail.com>
# SPDX-FileCopyrightText: 2020 ike709 <ike709@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 AJCM-git <60196617+AJCM-git@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 FL-OZ <58238103+FL-OZ@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2021 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024-2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Minemoder5000 <minemoder50000@gmail.com>
# SPDX-License-Identifier: MIT

- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 2.5h
  startingGear: StationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: StationEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: StationEngineerChameleonOutfit
  job: StationEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
