# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2023 brainfood1183
# SPDX-License-Identifier: MIT

- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    id: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn

- type: chameleonOutfit
  id: CluwneChameleonOutfit
  name: job-title-cluwne
  startingGear: CluwneGear
  icon: JobIconCluwne
  equipment:
    head: ClothingHeadHatXmasCrown
    eyes: ClothingEyesBlindfold
    ears: ClothingHeadsetGrey
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
