# SPDX-FileCopyrightText: 2026 ThatGuyUSA
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2025 keronshb
# SPDX-FileCopyrightText: 2025 Entvari
# SPDX-FileCopyrightText: 2025 Velken
# SPDX-FileCopyrightText: 2025 ScarKy0
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2021 Pancake
# SPDX-FileCopyrightText: 2022 Pancake
# SPDX-License-Identifier: MIT

#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    back: ClothingBackpack # Wizard backpack?
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: WizardPDA
    ears: ClothingHeadsetAltWizard
    belt: ClothingBeltWand
    pocket1: WizardTeleportScroll
    pocket2: WizardsGrimoire

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet

- type: chameleonOutfit
  id: WizardChameleonOutfit
  name: roles-antag-wizard-name
  startingGear: WizardBlueGear
  icon: "JobIconWizard"
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLGBTPin
    gloves: ClothingHandsGlovesColorBlack
