# SPDX-FileCopyrightText: 2024 SlamBamActionman
# SPDX-FileCopyrightText: 2025 SlamBamActionman
# SPDX-FileCopyrightText: 2024 Winkarst
# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2024 Ed
# SPDX-FileCopyrightText: 2024 LankLTE
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Kot
# SPDX-FileCopyrightText: 2024 deltanedas
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 SpaceCat
# SPDX-FileCopyrightText: 2023 Nairod
# SPDX-FileCopyrightText: 2023 lzk
# SPDX-FileCopyrightText: 2023 Maxtone
# SPDX-FileCopyrightText: 2023 lzk228
# SPDX-FileCopyrightText: 2023 Vasilis The Pikachu
# SPDX-FileCopyrightText: 2023 brainfood1183
# SPDX-FileCopyrightText: 2023 Puro
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Cheackraze
# SPDX-FileCopyrightText: 2022 LordEclipse
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-License-Identifier: MIT

- type: department
  id: Cargo
  name: department-Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - ServiceWorker

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden

- type: department
  id: Science
  name: department-Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  name: department-Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Reporter
  - Psychologist
  primary: false
