# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Emisse
# SPDX-License-Identifier: MIT

- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ReporterChameleonOutfit
  job: Reporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckTieRed
    gloves: ClothingHandsGlovesFingerless
