# SPDX-FileCopyrightText: 2025 Hitlinemoss
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2025 War Pigeon
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 Emisse
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 potato1234_x
# SPDX-FileCopyrightText: 2023 lzk
# SPDX-FileCopyrightText: 2023 crazybrain23
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Lamrr
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 wrexbe
# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2021 20kdc
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-License-Identifier: MIT

- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: CargoTechGear
  equipment:
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: CargoTechnicianChameleonOutfit
  job: CargoTechnician
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCargo
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesFingerless
