# SPDX-FileCopyrightText: 2025 deltanedas
# SPDX-FileCopyrightText: 2025 Unkn0wn_Gh0st
# SPDX-License-Identifier: MIT

# gloves
- type: entity
  parent: BaseAction
  id: ActionToggleKnuckleDustersStun
  name: Toggle stun knuckle dusters
  description: Toggles the duster's built in stun baton.
  components:
  - type: InstantAction
    event: !type:ToggleActionEvent
