# SPDX-FileCopyrightText: 2025 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Unkn0wn_Gh0st <shadowstalkermll@gmail.com>
# SPDX-License-Identifier: MIT

- type: entity
  parent: BaseAction
  id: ActionToggleKnuckleDustersStun
  name: Toggle stun knuckle dusters
  description: Toggles the duster's built in stun baton.
  components:
  - type: InstantAction
    event: !type:ToggleActionEvent
