# Everything we want to make roundstart instead of requiring a useless tech
- type: latheRecipePack
  id: MoffstationStatic
  recipes:
  - BoxShellTranquilizer
  - BoxBeanbag
  - ClothingBackpackElectropack
