# SPDX-FileCopyrightText: 2024 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 qrwas <aleksandr.vernigora93@gmail.com>
# SPDX-License-Identifier: MIT

- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 20h

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal
  groupBy: "jumpskirt"

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS
