# SPDX-FileCopyrightText: 2025 BruhIsaac
# SPDX-FileCopyrightText: 2024 HS
# SPDX-FileCopyrightText: 2024 no
# SPDX-License-Identifier: MIT

# for important antag roles (nukie reinforcements, ninja, etc.)
- type: ghostRoleRaffleSettings
  id: default
  settings:
    initialDuration: 45
    joinExtendsDurationBy: 2
    maxDuration: 45

# for roles that don't matter too much or are available plentifully (e.g. space carp)
- type: ghostRoleRaffleSettings
  id: short
  settings:
    initialDuration: 15
    joinExtendsDurationBy: 0
    maxDuration: 15
