# SPDX-FileCopyrightText: 2024 HS <81934438+HolySSSS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 no <165581243+pissdemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 BruhIsaac <dodgerike@yahoo.com>
# SPDX-License-Identifier: MIT

- type: ghostRoleRaffleSettings
  id: default
  settings:
    initialDuration: 45
    joinExtendsDurationBy: 2
    maxDuration: 45

# for roles that don't matter too much or are available plentifully (e.g. space carp)
- type: ghostRoleRaffleSettings
  id: short
  settings:
    initialDuration: 15
    joinExtendsDurationBy: 0
    maxDuration: 15
