# SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 UpAndLeaves <92269094+Alpha-Two@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Nox <nebulousnox38@gmail.com>
# SPDX-FileCopyrightText: 2026 ThatGuyUSA <thatguyusa123@gmail.com>
# SPDX-License-Identifier: MIT

- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconDeathSquad"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - WeaponPulsePistol
    - WeaponRevolverMatebaAP
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    - Hypospray
    - DeathAcidifierImplanter # crew will try to steal their amazing hardsuits
    - FreedomImplanter
  inhand:
  - WeaponPulseRifle

- type: chameleonOutfit
  id: DeathSquadChameleonOutfit
  job: DeathSquad
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitDeathsquad
    neck: ClothingNeckBronzeheart
