# SPDX-FileCopyrightText: 2025 Errant
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-License-Identifier: MIT

- type: jobRequirementOverride
  id: Reduced
  jobs:
    Captain:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 1h
