# SPDX-FileCopyrightText: 2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 keronshb <54602815+keronshb@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: roleType
  id: Neutral
  name: role-type-crew-aligned-name
  color: '#eeeeee'
  symbol: "ðŸ—¡" # Should never be antag, but just in case.

- type: roleType
  id: SoloAntagonist
  name: role-type-solo-antagonist-name
  color: '#d82000'
  symbol: "ðŸ—¡"

- type: roleType
  id: TeamAntagonist
  name: role-type-team-antagonist-name
  color: '#d82000'
  symbol: "âš”"

- type: roleType
  id: FreeAgent
  name: role-type-free-agent-name
  color: '#ffff00'
  symbol: "â˜¯"

- type: roleType
  id: Familiar
  name: role-type-familiar-name
  color: '#6495ed'
  symbol: "ðŸ—¡" # Should never be antag, but just in case.

- type: roleType
  id: Silicon
  name: role-type-silicon-name
  color: '#6495ed'
  symbol: "ðŸ—¡" # Should never be antag, but just in case.

- type: roleType
  id: SiliconAntagonist
  name: role-type-silicon-antagonist-name
  color: '#c832e6'
  symbol: "â›ž"
