# SPDX-FileCopyrightText: 2020, 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020-2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2020 20kdc <asdd2808@gmail.com>
# SPDX-FileCopyrightText: 2020 Peter Wedder <burneddi@gmail.com>
# SPDX-FileCopyrightText: 2021-2022 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2021 Elijahrane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Moony <moonheart08@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Morb <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Morber <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 War Pigeon <54217755+minus1over12@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds

- type: startingGear
  id: BotanistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BotanistChameleonOutfit
  job: Botanist
  equipment:
    head: ClothingHeadBandBotany
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterApronBotanist
    gloves: ClothingHandsGlovesLeather
