# SPDX-FileCopyrightText: 2025 Trosling
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2021 metalgearsloth
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Ephememory
# SPDX-FileCopyrightText: 2021 Rane
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Elijahrane
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-License-Identifier: MIT

- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampChaplain

- type: chameleonOutfit
  id: ChaplainChameleonOutfit
  job: Chaplain
  equipment:
    head: ClothingHeadHatPlaguedoctor
    eyes: ClothingEyesGlasses
    mask: ClothingMaskPlague
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterPlagueSuit
    gloves: ClothingHandsGlovesColorBlack

