# SPDX-FileCopyrightText: 2025 K-Dynamic
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2025 Errant
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2025 Minemoder5000
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Visne
# SPDX-FileCopyrightText: 2023 Flareguy
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2021 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Leon Friedrich
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Elijahrane
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 Peter Wedder
# SPDX-FileCopyrightText: 2020 VÃ­ctor Aguilera Puerto
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-License-Identifier: MIT

- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 0.5h
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesChef
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChefChameleonOutfit
  job: Chef
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef
