# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2022 metalgearsloth
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 Ubaser
# SPDX-FileCopyrightText: 2023 Velcroboy
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2022 Moony
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-FileCopyrightText: 2020 AJCM-git
# SPDX-FileCopyrightText: 2020 ike709
# SPDX-FileCopyrightText: 2020 FL-OZ
# SPDX-License-Identifier: MIT

- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  #storage:
    #back:
    #- Stuff

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    id: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled

- type: chameleonOutfit
  id: JanitorChameleonOutfit
  job: Janitor
  equipment:
    head: ClothingHeadHatPurplesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterWinterJani
    gloves: ClothingHandsGlovesJanitor
