# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2025 Errant
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2025 deltanedas
# SPDX-FileCopyrightText: 2025 SpeltIncorrectyl
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2024 Wrexbe (Josh)
# SPDX-FileCopyrightText: 2024 brainfood1183
# SPDX-FileCopyrightText: 2020 DrSmugleaf
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2023 Chief-Engineer
# SPDX-FileCopyrightText: 2023 lzk228
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Moony
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2020 Swept
# SPDX-FileCopyrightText: 2021 Swept
# SPDX-FileCopyrightText: 2020 20kdc
# SPDX-License-Identifier: MIT

- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime
  playTimeTracker: JobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4h
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers
      preventWriting: true
    - type: FrenchAccent

- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    id: MimePDA
    pocket1: CrayonMime
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  parent: BaseAction
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: Action
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
  - type: InstantAction
    event: !type:InvisibleWallActionEvent

- type: chameleonOutfit
  id: MimeChameleonOutfit
  job: Mime
  equipment:
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckScarfStripedZebra
    outerClothing: ClothingOuterWinterMime
