# SPDX-FileCopyrightText: 2025 Boaz1111
# SPDX-FileCopyrightText: 2025 beck-thompson
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2024 Cojoke
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 Nemanja
# SPDX-FileCopyrightText: 2023 Whisper
# SPDX-FileCopyrightText: 2023 PrPleGoo
# SPDX-FileCopyrightText: 2022 Kara
# SPDX-FileCopyrightText: 2022 Morb
# SPDX-FileCopyrightText: 2022 ZeroDiamond
# SPDX-FileCopyrightText: 2022 Pieter-Jan Briers
# SPDX-FileCopyrightText: 2022 Morber
# SPDX-FileCopyrightText: 2022 Rane
# SPDX-FileCopyrightText: 2022 Chris V
# SPDX-License-Identifier: MIT

- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hire
  access:
  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
  - Theatre
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer

- type: startingGear
  id: MusicianGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MusicianChameleonOutfit
  job: Musician
  equipment:
    head: ClothingHeadHatTophat
    mask: ClothingMaskBreath
    neck: ClothingMultipleHeadphones
    outerClothing: ClothingOuterWinterMusician
    gloves: ClothingHandsGlovesColorBlack
