# SPDX-FileCopyrightText: 2025 B_Kirill
# SPDX-FileCopyrightText: 2024 slarticodefast
# SPDX-FileCopyrightText: 2024 AJCM-git
# SPDX-FileCopyrightText: 2024 Golinth
# SPDX-FileCopyrightText: 2024 PrPleGoo
# SPDX-FileCopyrightText: 2024 Baptr0b0t
# SPDX-FileCopyrightText: 2024 Arendian
# SPDX-License-Identifier: MIT

- type: securityIcon
  id: SecurityIcon
  abstract: true
  priority: 3
  offset: 1
  locationPreference: Right
  isShaded: true

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconDischarged
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_discharged

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconIncarcerated
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_incarcerated

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconParoled
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_paroled

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconSuspected
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_suspected
  
- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconHostile
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_hostile

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconEliminated
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_eliminated

- type: securityIcon
  parent: SecurityIcon
  id: SecurityIconWanted
  icon:
    sprite: /Textures/Interface/Misc/security_icons.rsi
    state: hud_wanted

- type: securityIcon
  id: MindShieldIcon
  priority: 2
  locationPreference: Right
  layer: Mod
  isShaded: true
  icon:
    sprite: /Textures/Interface/Misc/job_icons.rsi
    state: MindShield
