# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 PrPleGoo <PrPleGoo@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024-2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PotentiallyTom <67602105+PotentiallyTom@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 beck-thompson <107373427+beck-thompson@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Minemoder5000 <minemoder50000@gmail.com>
# SPDX-FileCopyrightText: 2026 Kowlin <10947836+Kowlin@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 10h
      inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: false
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ResearchAssistantChameleonOutfit
  job: ResearchAssistant
  equipment:
    head: ClothingHeadHatCardborg
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
