# SPDX-FileCopyrightText: 2026 ThatGuyUSA
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 metalgearsloth
# SPDX-FileCopyrightText: 2023 brainfood1183
# SPDX-FileCopyrightText: 2023 DrSmugleaf
# SPDX-FileCopyrightText: 2023 lzk
# SPDX-License-Identifier: MIT

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricord
    outerClothing: ClothingOuterCoatGentle

- type: chameleonOutfit
  id: PirateChameleonOutfit
  name: roles-antag-pirate-name
  icon: "JobIconPirate"
  startingGear: PirateFirstmateGear
  equipment:
    eyes: ClothingEyesEyepatch
    ears: ClothingHeadsetFreelance
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckBling
    gloves: ClothingHandsGlovesColorLightBrown
    outerClothing: ClothingOuterCoatPirate

