# SPDX-FileCopyrightText: 2023 brainfood1183 <113240905+brainfood1183@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 ThatGuyUSA <thatguyusa123@gmail.com>
# SPDX-License-Identifier: MIT

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate

- type: startingGear
  id: PirateFirstmateGear
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricord
    outerClothing: ClothingOuterCoatGentle

- type: chameleonOutfit
  id: PirateChameleonOutfit
  name: roles-antag-pirate-name
  icon: "JobIconPirate"
  startingGear: PirateFirstmateGear
  equipment:
    eyes: ClothingEyesEyepatch
    ears: ClothingHeadsetFreelance
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckBling
    gloves: ClothingHandsGlovesColorLightBrown
    outerClothing: ClothingOuterCoatPirate

