# SPDX-FileCopyrightText: 2025 Errant
# SPDX-FileCopyrightText: 2025 ScarKy0
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2023 coolmankid12345
# SPDX-License-Identifier: MIT

- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
