# SPDX-FileCopyrightText: 2025 Errant
# SPDX-FileCopyrightText: 2025 ArtisticRoomba
# SPDX-FileCopyrightText: 2025 ScarKy0
# SPDX-FileCopyrightText: 2025 Alpha-Two
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2023 Ed
# SPDX-FileCopyrightText: 2024 Ed
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 lapatison
# SPDX-License-Identifier: MIT

- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
