# SPDX-FileCopyrightText: 2023-2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 lapatison <100279397+lapatison@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ScarKy0 <106310278+ScarKy0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Alpha-Two <92269094+Alpha-Two@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: startingGear
  id: ThiefGear
  storage:
    back:
    - ThiefBeacon
    - SatchelThief
