# SPDX-FileCopyrightText: 2025 Samuka <47865393+Samuka-C@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: antag
  id: MothershipCore
  name: roles-antag-mothership-core-name
  antagonist: true
  setPreference: true
  objective: roles-antag-mothership-core-objective
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs
  guides: [ Xenoborgs ]

- type: antag
  id: Xenoborg
  name: roles-antag-xenoborg-name
  antagonist: true
  setPreference: true
  objective: roles-antag-xenoborg-objective
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs
  guides: [ Xenoborgs ]
