# SPDX-FileCopyrightText: 2022 Morb <14136326+Morb0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Errant <35878406+Errant-4@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ScarKy0 <106310278+ScarKy0@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  guides: [ Zombies ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
  guides: [ Zombies ]
