# Tourist
- type: entity
  parent: BaseMindRole
  id: MindRoleTourist
  name: Tourist Role
  components:
  - type: MindRole
    antag: true
    antagPrototype: Tourist
    roleType: FreeAgent
  - type: TouristRole
